// Data compiled from SAIS-CARI (Johns Hopkins) construction-contract-revenue dataset
// and AidData's Global Chinese Development Finance Dataset v3.0. See APP_DATA.meta.sources.
const APP_DATA = {
  "meta": {
    "title": "China in Algeria — Contracts, Finance & Flagship Projects, 1998–2024",
    "generated": "2026-08-28",
    "sources": [
      {
        "name": "SAIS-CARI, Johns Hopkins University — Chinese Construction Contract Revenue in Africa (updated Nov 2025)",
        "url": "https://www.sais-cari.org/data-chinese-contracts-in-africa"
      },
      {
        "name": "AidData — Global Chinese Development Finance Dataset, Version 3.0",
        "url": "https://www.aiddata.org/data/aiddatas-global-chinese-development-finance-dataset-version-3-0"
      }
    ]
  },
  "years": [
    1998,
    1999,
    2000,
    2001,
    2002,
    2003,
    2004,
    2005,
    2006,
    2007,
    2008,
    2009,
    2010,
    2011,
    2012,
    2013,
    2014,
    2015,
    2016,
    2017,
    2018,
    2019,
    2020,
    2021,
    2022,
    2023,
    2024
  ],
  "countries": [
    "Algeria",
    "Egypt",
    "Morocco",
    "Tunisia",
    "Libya"
  ],
  "countryColor": {
    "Algeria": "#ff6a3d",
    "Egypt": "#4a90d9",
    "Morocco": "#3fb68a",
    "Tunisia": "#e8a33d",
    "Libya": "#b07cd9"
  },
  "contractRevenue": {
    "Algeria": [
      78.6,
      89.6,
      38.4,
      90.2,
      211.6,
      471.8,
      805.3,
      1050.4,
      1686.1,
      2340.3,
      4202.3,
      5877.3,
      4947.4,
      4052.6,
      4465.5,
      5197.6,
      6334.3,
      8240.6,
      8434.2,
      7849,
      7521.5,
      6335.5,
      4688.1,
      3824.2,
      2843.3,
      3421.2,
      5268.7
    ],
    "Egypt": [
      20.8,
      15.1,
      7.2,
      10.4,
      30.2,
      23.7,
      73.8,
      276.5,
      337.5,
      391.9,
      513.8,
      797.4,
      1168.8,
      1023.7,
      969,
      1028.1,
      924,
      2017.8,
      2281.1,
      1541.8,
      2045.6,
      3189.6,
      2993.4,
      1945.5,
      2734.9,
      3241.6,
      3254.4
    ],
    "Morocco": [
      8.7,
      1.2,
      4.8,
      24.7,
      25.3,
      34.2,
      37.6,
      45.6,
      225.5,
      309,
      280.4,
      511,
      590.4,
      381.4,
      423.2,
      362.5,
      607,
      1131.1,
      766.7,
      376.5,
      683,
      335.3,
      219.8,
      223.6,
      242.2,
      395.1,
      396.6
    ],
    "Tunisia": [
      0,
      10,
      3.5,
      9.8,
      34.3,
      24.3,
      40.4,
      60.9,
      38.8,
      35.5,
      53.5,
      53.2,
      148,
      95.8,
      109.9,
      132.9,
      117.2,
      110.7,
      135.9,
      219,
      111.5,
      93.7,
      85.2,
      120.8,
      94.9,
      68,
      76.7
    ],
    "Libya": [
      3.6,
      2.9,
      2,
      2.4,
      14.8,
      155,
      66.7,
      127.9,
      225.4,
      263,
      741.2,
      1912.5,
      3449.3,
      804.2,
      52.6,
      563.6,
      156.2,
      173.8,
      32.1,
      51.2,
      1.1,
      21.1,
      0,
      11.5,
      20,
      65.7,
      129.8
    ]
  },
  "cumulativeRevenue": {
    "Algeria": [
      78.6,
      168.2,
      206.6,
      296.8,
      508.4,
      980.2,
      1785.5,
      2835.9,
      4522,
      6862.3,
      11064.6,
      16941.9,
      21889.3,
      25941.9,
      30407.4,
      35605,
      41939.3,
      50179.9,
      58614.1,
      66463.1,
      73984.6,
      80320.1,
      85008.2,
      88832.4,
      91675.7,
      95096.9,
      100365.6
    ],
    "Egypt": [
      20.8,
      35.9,
      43.1,
      53.5,
      83.7,
      107.4,
      181.2,
      457.7,
      795.2,
      1187.1,
      1700.9,
      2498.3,
      3667.1,
      4690.8,
      5659.8,
      6687.9,
      7611.9,
      9629.7,
      11910.8,
      13452.6,
      15498.2,
      18687.8,
      21681.2,
      23626.7,
      26361.6,
      29603.2,
      32857.6
    ],
    "Morocco": [
      8.7,
      9.9,
      14.7,
      39.4,
      64.7,
      98.9,
      136.5,
      182.1,
      407.6,
      716.6,
      997,
      1508,
      2098.4,
      2479.8,
      2903,
      3265.5,
      3872.5,
      5003.6,
      5770.3,
      6146.8,
      6829.8,
      7165.1,
      7384.9,
      7608.5,
      7850.7,
      8245.8,
      8642.4
    ],
    "Tunisia": [
      0,
      10,
      13.5,
      23.3,
      57.6,
      81.9,
      122.3,
      183.2,
      222,
      257.5,
      311,
      364.2,
      512.2,
      608,
      717.9,
      850.8,
      968,
      1078.7,
      1214.6,
      1433.6,
      1545.1,
      1638.8,
      1724,
      1844.8,
      1939.7,
      2007.7,
      2084.4
    ],
    "Libya": [
      3.6,
      6.5,
      8.5,
      10.9,
      25.7,
      180.7,
      247.4,
      375.3,
      600.7,
      863.7,
      1604.9,
      3517.4,
      6966.7,
      7770.9,
      7823.5,
      8387.1,
      8543.3,
      8717.1,
      8749.2,
      8800.4,
      8801.5,
      8822.6,
      8822.6,
      8834.1,
      8854.1,
      8919.8,
      9049.6
    ]
  },
  "africaTotal": [
    1870.6,
    1827.7,
    1096.2,
    1524.1,
    1813.5,
    2601.3,
    3811.6,
    6091.7,
    9324.1,
    12376.1,
    19749.1,
    28099,
    35830.2,
    36121.9,
    40757.9,
    47890.7,
    52974.4,
    55887.6,
    51450.3,
    51187.9,
    48838.7,
    46012.6,
    38149,
    37115.6,
    37844.4,
    37425.2,
    40361
  ],
  "algeriaRank": [
    7,
    4,
    10,
    4,
    2,
    2,
    1,
    2,
    2,
    1,
    1,
    1,
    2,
    2,
    3,
    2,
    3,
    1,
    1,
    1,
    1,
    1,
    1,
    2,
    3,
    2,
    1
  ],
  "africaCountryCount": [
    56,
    56,
    56,
    56,
    56,
    56,
    56,
    56,
    56,
    56,
    56,
    56,
    56,
    56,
    56,
    56,
    56,
    56,
    56,
    56,
    56,
    56,
    56,
    56,
    56,
    56,
    56
  ],
  "rankByCountry": {
    "Algeria": [
      7,
      4,
      10,
      4,
      2,
      2,
      1,
      2,
      2,
      1,
      1,
      1,
      2,
      2,
      3,
      2,
      3,
      1,
      1,
      1,
      1,
      1,
      1,
      2,
      3,
      2,
      1
    ],
    "Egypt": [
      19,
      23,
      29,
      30,
      16,
      22,
      10,
      5,
      5,
      6,
      9,
      9,
      10,
      9,
      12,
      14,
      16,
      7,
      6,
      9,
      8,
      4,
      3,
      7,
      4,
      3,
      3
    ],
    "Morocco": [
      30,
      43,
      35,
      19,
      17,
      14,
      18,
      21,
      8,
      7,
      14,
      14,
      17,
      22,
      21,
      25,
      21,
      18,
      19,
      25,
      18,
      26,
      30,
      31,
      31,
      24,
      23
    ],
    "Tunisia": [
      55,
      27,
      37,
      32,
      12,
      20,
      17,
      19,
      29,
      32,
      30,
      35,
      26,
      36,
      35,
      39,
      42,
      40,
      35,
      33,
      39,
      40,
      38,
      37,
      38,
      42,
      42
    ],
    "Libya": [
      38,
      38,
      40,
      42,
      25,
      5,
      12,
      10,
      9,
      11,
      6,
      5,
      3,
      14,
      42,
      18,
      37,
      37,
      44,
      42,
      53,
      48,
      52,
      50,
      49,
      43,
      39
    ]
  },
  "shareByCountry": {
    "Algeria": [
      4.2,
      4.9,
      3.5,
      5.9,
      11.7,
      18.1,
      21.1,
      17.2,
      18.1,
      18.9,
      21.3,
      20.9,
      13.8,
      11.2,
      11,
      10.9,
      12,
      14.7,
      16.4,
      15.3,
      15.4,
      13.8,
      12.3,
      10.3,
      7.5,
      9.1,
      13.1
    ],
    "Egypt": [
      1.1,
      0.8,
      0.7,
      0.7,
      1.7,
      0.9,
      1.9,
      4.5,
      3.6,
      3.2,
      2.6,
      2.8,
      3.3,
      2.8,
      2.4,
      2.1,
      1.7,
      3.6,
      4.4,
      3,
      4.2,
      6.9,
      7.8,
      5.2,
      7.2,
      8.7,
      8.1
    ],
    "Morocco": [
      0.5,
      0.1,
      0.4,
      1.6,
      1.4,
      1.3,
      1,
      0.7,
      2.4,
      2.5,
      1.4,
      1.8,
      1.6,
      1.1,
      1,
      0.8,
      1.1,
      2,
      1.5,
      0.7,
      1.4,
      0.7,
      0.6,
      0.6,
      0.6,
      1.1,
      1
    ],
    "Tunisia": [
      0,
      0.5,
      0.3,
      0.6,
      1.9,
      0.9,
      1.1,
      1,
      0.4,
      0.3,
      0.3,
      0.2,
      0.4,
      0.3,
      0.3,
      0.3,
      0.2,
      0.2,
      0.3,
      0.4,
      0.2,
      0.2,
      0.2,
      0.3,
      0.3,
      0.2,
      0.2
    ],
    "Libya": [
      0.2,
      0.2,
      0.2,
      0.2,
      0.8,
      6,
      1.7,
      2.1,
      2.4,
      2.1,
      3.8,
      6.8,
      9.6,
      2.2,
      0.1,
      1.2,
      0.3,
      0.3,
      0.1,
      0.1,
      0,
      0,
      0,
      0,
      0.1,
      0.2,
      0.3
    ]
  },
  "flagshipProjects": [
    {
      "id": "mosque",
      "name": "Grand Mosque of Algiers (Djamaa el Djazaïr)",
      "sector": "Religious / civic architecture",
      "contractor": "China State Construction Engineering Corporation (CSCEC)",
      "financier": "Algerian state budget (hydrocarbon revenue)",
      "valueUSD": 898000000,
      "valueNote": "~$898M widely cited; Algeria Press Service puts it at €898M (≈$974M)",
      "yearStart": 2012,
      "yearEnd": 2019,
      "status": "completed",
      "statusLabel": "Completed",
      "description": "Africa's largest mosque and the world's third-largest, with a 265m minaret — the tallest religious structure in the world. The structure was finished in 2019 and opened for prayers in October 2020, but its official state inauguration — delayed by the 2019 political upheaval that ousted the project's original sponsor, President Bouteflika — didn't happen until President Tebboune presided over it on February 26, 2024.",
      "sources": [
        {
          "title": "Smithsonian Magazine — Algeria Inaugurates the Largest Mosque in Africa",
          "url": "https://www.smithsonianmag.com/smart-news/algeria-officially-inaugurates-the-largest-mosque-in-africa-180983880/"
        },
        {
          "title": "Al-Monitor — What we know about Algeria’s mega mosque",
          "url": "https://www.al-monitor.com/originals/2024/02/what-we-know-about-algerias-mega-mosque-largest-africa"
        }
      ]
    },
    {
      "id": "highway",
      "name": "East–West Highway",
      "sector": "Transport infrastructure",
      "contractor": "CITIC–CRCC consortium (central & western sections, 528 km)",
      "financier": "Algerian state budget (hydrocarbon revenue)",
      "valueUSD": 11400000000,
      "valueNote": "~$11.4B total project; ~$6.2B contract for the CITIC–CRCC-built sections",
      "yearStart": 2007,
      "yearEnd": 2023,
      "status": "completed-scandal",
      "statusLabel": "Completed — corruption scandal",
      "description": "1,216 km six-lane highway from the Moroccan to the Tunisian border, one of the largest public-works contracts ever awarded globally. The Chinese CITIC–CRCC consortium built the central and western sections (528 km); a Japanese consortium (COJAAL) built the east. A kickback scandal — dubbed the \"scandal of the century\" in Algerian media — led to a May 2015 court verdict jailing 14 people (two for 10 years) and fining seven foreign contractors, including CITIC–CRCC, roughly $56.4M each (~$390M total). The final 84km stretch was delivered in August 2023, 17 years after the project launched.",
      "sources": [
        {
          "title": "Middle East Eye — 14 jailed and foreign firms fined $390mn in Algeria’s ‘scandal of the century’",
          "url": "https://www.middleeasteye.net/news/14-jailed-and-foreign-firms-fined-390mn-algerias-scandal-century"
        },
        {
          "title": "Xinhua — CITIC delivers final section of Algeria’s East-West Highway",
          "url": "https://english.news.cn/africa/20230813/65019ea47ba24121b241f2dba7fe0801/c.html"
        },
        {
          "title": "Wikipedia — East–West Highway (Algeria)",
          "url": "https://en.wikipedia.org/wiki/East%E2%80%93West_Highway_(Algeria)"
        }
      ]
    },
    {
      "id": "airport",
      "name": "Algiers Houari Boumédiène Airport — New Terminal",
      "sector": "Transport infrastructure",
      "contractor": "China State Construction Engineering Corporation (CSCEC)",
      "financier": "Algerian state budget (hydrocarbon revenue)",
      "valueUSD": 865000000,
      "valueNote": "€650M contract (~$865M at 2014 exchange rates)",
      "yearStart": 2014,
      "yearEnd": 2019,
      "status": "completed",
      "statusLabel": "Completed",
      "description": "A 650,000 m² new international terminal with 10 million passengers/year capacity — CSCEC's first airport project as general contractor outside China, and the largest civil-aviation project ever built in Algeria. The €650M contract was awarded to CSCEC in 2014, originally targeting a 2018 completion; the terminal opened in 2019 after delays.",
      "sources": [
        {
          "title": "CSCEC — The Algiers New Airport Project",
          "url": "https://en.cscec.com/cpth/HQD/202401/3746673.html"
        },
        {
          "title": "Oxford Business Group — Algeria infrastructure development attracts foreign bidders",
          "url": "https://oxfordbusinessgroup.com/reports/algeria/2014-report/economy/despite-regulatory-challenges-public-investment-in-infrastructure-development-continues-to-attract-foreign-bidders"
        }
      ]
    },
    {
      "id": "port",
      "name": "El Hamdania Deep-Water Port, Cherchell",
      "sector": "Port infrastructure",
      "contractor": "China State Construction Engineering Corp. + China Harbour Engineering Co.",
      "financier": "China Eximbank (pledged loan)",
      "valueUSD": 3400000000,
      "valueNote": "~$3–5B pledged across differing estimates (AidData tracks $3.4–3.7B pledged financing)",
      "yearStart": 2016,
      "yearEnd": 2025,
      "status": "cancelled",
      "statusLabel": "Cancelled (March 2025)",
      "description": "A planned 26-million-tonne/year container port and free-trade zone roughly 50–70km west of Algiers near Cherchell, to be operated for 25 years by Shanghai Ports International under the original 2016 deal. The project was suspended in 2019 amid Algeria's political upheaval and never restarted at scale; officials and analysts blamed weak project-management capacity, infighting between vested interests, corruption, and political instability, compounded by a severe fiscal squeeze (Algeria's 2025 budget deficit ran to roughly 22% of GDP). It was formally shelved in March 2025. Some reporting also links the decision to Chinese financing terms seen as one-sided (reportedly requiring Chinese contractors only) and to Algeria's parallel efforts to warm relations with France — those two angles are more loosely sourced than the management and fiscal reasons above.",
      "sources": [
        {
          "title": "AGBI — Algeria cancels deep-water port project with China",
          "url": "https://www.agbi.com/infrastructure/2025/03/algeria-cancels-deep-water-port-project-with-china/"
        },
        {
          "title": "The Geopolitical Desk — Why Algeria pulled the plug on its mega-port dream",
          "url": "https://www.thegeopoliticaldesk.com/why-algeria-pulled-the-plug-on-its-mega-port-dream/"
        },
        {
          "title": "The Arab Weekly — Algeria withdraws Hamdania port deal from China",
          "url": "https://thearabweekly.com/algeria-withdraws-hamdania-port-deal-china-ease-tensions-france"
        },
        {
          "title": "AidData project record #43781",
          "url": "https://china.aiddata.org/projects/43781"
        }
      ]
    }
  ],
  "financing": {
    "totalRecords": 57,
    "recommendedTotalUSD": 310574108,
    "grantValueUSD": 196745833,
    "loanValueUSD": 113828275,
    "allRecordsTotalUSD": 4226441071,
    "bySector": {
      "HEALTH": 68790471,
      "AGRICULTURE, FORESTRY, FISHING": 2848473,
      "EMERGENCY RESPONSE": 1565046,
      "EDUCATION": 65434,
      "OTHER SOCIAL INFRASTRUCTURE AND SERVICES": 117738388,
      "GOVERNMENT AND CIVIL SOCIETY": 65107000,
      "DISASTER PREVENTION AND PREPAREDNESS": 4838389,
      "COMMUNICATIONS": 49620907
    },
    "byStatus": {
      "Completion": 40,
      "Implementation": 6,
      "Pipeline: Commitment": 9,
      "Pipeline: Pledge": 2
    },
    "byFlowType": {
      "Grant": 48,
      "Loan": 8,
      "Vague": 1
    },
    "projects": [
      {
        "id": 94808,
        "year": 2021,
        "title": "Chinese Government donates 200,000 Sinopharm vaccines worth $3.6 million in February 2021 (Linked to Project ID#97169)",
        "sector": "HEALTH",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 3600000,
        "recommended": true,
        "funder": "Unspecified Chinese Government Institution",
        "recipient": "Government of Algeria"
      },
      {
        "id": 94952,
        "year": 2021,
        "title": "Hubei Health Comission sends 26th medical team to Algeria",
        "sector": "HEALTH",
        "flowType": "Grant",
        "status": "Implementation",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Hubei Province Health Commission",
        "recipient": "Government of Algeria"
      },
      {
        "id": 97169,
        "year": 2021,
        "title": "Chinese Government donates 3.2 million Sinovac Covid-19 vaccine doses worth $57.6 million in September 2021 (Linked to Project ID#94808)",
        "sector": "HEALTH",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 57600000,
        "recommended": true,
        "funder": "Unspecified Chinese Government Institution",
        "recipient": "Government of Algeria"
      },
      {
        "id": 94784,
        "year": 2020,
        "title": " CSCEC donates anti-epidemic medical supplies worth USD $450,000 to Algeria in March 2020 (Linked to Project ID#95424)",
        "sector": "HEALTH",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 502577,
        "recommended": true,
        "funder": "China State Construction Engineering Corporation (CSCEC)",
        "recipient": "Government of Algeria"
      },
      {
        "id": 94790,
        "year": 2020,
        "title": "Chinese government provides donation of of anti-epidemic medical supplies to Algeria in April 2020",
        "sector": "HEALTH",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Unspecified Chinese Government Institution",
        "recipient": "Government of Algeria"
      },
      {
        "id": 94792,
        "year": 2020,
        "title": "China Railway Construction Corporation donates 100 ventilators to Algeria in April 2020",
        "sector": "HEALTH",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 3170030,
        "recommended": true,
        "funder": "China Railway Construction Corporation (CRCC)",
        "recipient": "Government of Algeria"
      },
      {
        "id": 94795,
        "year": 2020,
        "title": "Chinese government provides donation of of anti-epidemic medical supplies to Algeria in April 2020 ",
        "sector": "HEALTH",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Unspecified Chinese Government Institution",
        "recipient": "Government of Algeria"
      },
      {
        "id": 94806,
        "year": 2020,
        "title": "Chinese government donates anti-epidemic supplies in May 2020",
        "sector": "HEALTH",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 3917864,
        "recommended": true,
        "funder": "Unspecified Chinese Government Institution",
        "recipient": "Government of Algeria"
      },
      {
        "id": 94807,
        "year": 2020,
        "title": "Chinese government sends anti-epidemic medical team to Algeria in May 2020",
        "sector": "HEALTH",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "National Health Commission of China",
        "recipient": "Government of Algeria"
      },
      {
        "id": 95094,
        "year": 2020,
        "title": "China provides RMB 100M Yuan in an October 2020 ETCA for Unspecified Projects",
        "sector": "UNALLOCATED/UNSPECIFIED",
        "flowType": "Grant",
        "status": "Pipeline: Commitment",
        "amountUSD": 16186044,
        "recommended": false,
        "funder": "China Ministry of Commerce",
        "recipient": "Government of Algeria"
      },
      {
        "id": 95424,
        "year": 2020,
        "title": "Chinese medical team provides technical assistance to Algeria beginning March 2020 (Linked to Project ID#94784)",
        "sector": "HEALTH",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Unspecified Chinese Government Institution",
        "recipient": "Government of Algeria"
      },
      {
        "id": 89651,
        "year": 2019,
        "title": "Chinese Government dispatches 26th medical team to Algeria",
        "sector": "HEALTH",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Unspecified Chinese Government Institution",
        "recipient": "Government of Algeria"
      },
      {
        "id": 89652,
        "year": 2019,
        "title": "Chinese Embassy donates 200,000 plants to Algeria",
        "sector": "AGRICULTURE, FORESTRY, FISHING",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Chinese Embassy",
        "recipient": "Government of Algeria|National Reforestation Programme (NRP)"
      },
      {
        "id": 61139,
        "year": 2018,
        "title": "Chinese Embassy donates 10m DZD to the Sahrawi Red Crescent to aid refugees in the camps of Tindouf",
        "sector": "EMERGENCY RESPONSE",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 93477,
        "recommended": true,
        "funder": "Chinese Embassy",
        "recipient": "Algerian Red Crescent Society (ARCS)|Sahrawi Red Crescent Society (SRCS)"
      },
      {
        "id": 61229,
        "year": 2018,
        "title": "China Ministry of Commerce grants 200 million RMB to Algeria for unspecified purposes through November 2018 ETCA",
        "sector": "UNALLOCATED/UNSPECIFIED",
        "flowType": "Grant",
        "status": "Pipeline: Commitment",
        "amountUSD": 32956577,
        "recommended": false,
        "funder": "China Ministry of Commerce",
        "recipient": "Government of Algeria"
      },
      {
        "id": 62317,
        "year": 2018,
        "title": "Chinese Embassy grants 7m DZD to Algerian Red Crescent for purchase of a school bus",
        "sector": "EDUCATION",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 65434,
        "recommended": true,
        "funder": "Chinese Embassy",
        "recipient": "Algerian Red Crescent Society (ARCS)"
      },
      {
        "id": 43781,
        "year": 2017,
        "title": "China Eximbank pledges loan for El Hamdania Deepwater Container Port Infrastructure Project",
        "sector": "TRANSPORT AND STORAGE",
        "flowType": "Loan",
        "status": "Pipeline: Pledge",
        "amountUSD": 3716290556,
        "recommended": false,
        "funder": "Export-Import Bank of China (China Eximbank)",
        "recipient": "Joint Venture of SERPORT, CSCEC, and CHEC"
      },
      {
        "id": 61201,
        "year": 2017,
        "title": "Chinese Government provides RMB 200 million grant — via ETCA — for Youth Culture and Leisure Complex Construction Project (Linked to Project ID#52453)",
        "sector": "OTHER SOCIAL INFRASTRUCTURE AND SERVICES",
        "flowType": "Grant",
        "status": "Implementation",
        "amountUSD": 34105728,
        "recommended": true,
        "funder": "China Ministry of Commerce",
        "recipient": "Government of Algeria"
      },
      {
        "id": 52453,
        "year": 2016,
        "title": "Chinese Government provides RMB 100 million grant — via ETCA — for Youth Culture and Leisure Complex Construction Project (Linked to Project ID#61201)",
        "sector": "OTHER SOCIAL INFRASTRUCTURE AND SERVICES",
        "flowType": "Grant",
        "status": "Implementation",
        "amountUSD": 17769640,
        "recommended": true,
        "funder": "China Ministry of Commerce",
        "recipient": "Government of Algeria"
      },
      {
        "id": 52461,
        "year": 2016,
        "title": "Chinese Embassy donates 50 sacrificial animals to needy families in Beni Milek",
        "sector": "DEVELOPMENTAL FOOD AID/FOOD SECURITY ASSISTANCE",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Chinese Embassy",
        "recipient": "Algerian Red Crescent Society (ARCS)"
      },
      {
        "id": 53202,
        "year": 2016,
        "title": "Chinese Government provides RMB 16.03 million grant — via ETCA — for Phase 2 of Saline Farmland Improvement Project",
        "sector": "AGRICULTURE, FORESTRY, FISHING",
        "flowType": "Grant",
        "status": "Implementation",
        "amountUSD": 2848473,
        "recommended": true,
        "funder": "China Ministry of Commerce",
        "recipient": "Government of Algeria"
      },
      {
        "id": 53180,
        "year": 2015,
        "title": "Chinese Embassy donates livestock to households in Tizi Ouzou Province",
        "sector": "DEVELOPMENTAL FOOD AID/FOOD SECURITY ASSISTANCE",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Chinese Embassy",
        "recipient": "Algerian Red Crescent Society (ARCS)"
      },
      {
        "id": 62307,
        "year": 2015,
        "title": "Chinese Government dispatches 25th medical team to Algiers, Aïn Defla, Tiaret, Sétif, Khenchela, Batna, Mascara, and Saïda",
        "sector": "HEALTH",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Unspecified Chinese Government Institution",
        "recipient": "Government of Algeria"
      },
      {
        "id": 65976,
        "year": 2015,
        "title": "Chinese Academy of Governance Signs Partnership With Algerian Interior Ministry for Civil Service Training",
        "sector": "GOVERNMENT AND CIVIL SOCIETY",
        "flowType": "Grant",
        "status": "Implementation",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Unspecified Chinese Government Institution",
        "recipient": ""
      },
      {
        "id": 66086,
        "year": 2015,
        "title": "China Eximbank provides loan to Anhui Construction Engineering Group for University Housing Construction Project",
        "sector": "OTHER SOCIAL INFRASTRUCTURE AND SERVICES",
        "flowType": "Loan",
        "status": "Pipeline: Commitment",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Export-Import Bank of China (China Eximbank)",
        "recipient": "Anhui Construction Engineering Group"
      },
      {
        "id": 62291,
        "year": 2014,
        "title": "Chinese Government dispatches 24th medical team to Algiers, Aïn Defla, Tiaret, Sétif, Khenchela, Batna, Mascara, and Saïda",
        "sector": "HEALTH",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Unspecified Chinese Government Institution",
        "recipient": "Government of Algeria"
      },
      {
        "id": 85236,
        "year": 2013,
        "title": "Chinese Government dispatches 23rd medical team to Algiers, Aïn Defla, Tiaret, Sétif, Khenchela, Batna, Mascara, and Saïda",
        "sector": "HEALTH",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Unspecified Chinese Government Institution",
        "recipient": "Government of Algeria"
      },
      {
        "id": 31780,
        "year": 2012,
        "title": "Chinese Government provides grant for Solar Street Lighting Project",
        "sector": "ENERGY",
        "flowType": "Grant",
        "status": "Pipeline: Commitment",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Unspecified Chinese Government Institution",
        "recipient": "Government of Algeria"
      },
      {
        "id": 61073,
        "year": 2012,
        "title": "Chinese Government provides RMB 100 million grant — via ETCA — for unspecified purposes",
        "sector": "UNALLOCATED/UNSPECIFIED",
        "flowType": "Grant",
        "status": "Pipeline: Commitment",
        "amountUSD": 18611390,
        "recommended": false,
        "funder": "China Ministry of Commerce",
        "recipient": "Government of Algeria"
      },
      {
        "id": 62670,
        "year": 2012,
        "title": "China Eximbank provides a loan in support of the 10,000 Housing Units Project",
        "sector": "OTHER SOCIAL INFRASTRUCTURE AND SERVICES",
        "flowType": "Loan",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Export-Import Bank of China (China Eximbank)",
        "recipient": "Government of Algeria"
      },
      {
        "id": 62368,
        "year": 2011,
        "title": "Chinese Government provides grant — via ETCA — for unspecified purposes",
        "sector": "UNALLOCATED/UNSPECIFIED",
        "flowType": "Grant",
        "status": "Pipeline: Commitment",
        "amountUSD": 0,
        "recommended": false,
        "funder": "China Ministry of Commerce",
        "recipient": "Government of Algeria"
      },
      {
        "id": 523,
        "year": 2010,
        "title": "MOFCOM provides RMB 320 million grant for Opera House Construction Project",
        "sector": "OTHER SOCIAL INFRASTRUCTURE AND SERVICES",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 65839365,
        "recommended": true,
        "funder": "China Ministry of Commerce",
        "recipient": "Government of Algeria"
      },
      {
        "id": 31758,
        "year": 2010,
        "title": "Chinese Embassy in Algeria and 22 Chinese state-owned enterprises provide funding and in-kind donations for China-Algeria Friendship Park",
        "sector": "OTHER SOCIAL INFRASTRUCTURE AND SERVICES",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "China Civil Engineering Construction Corporation (CCECC)|China National Petroleum Corporation (CNPC)|China Petroleum & Chemical Corporation (Sinopec Ltd.)|China Railway Construction Corporation (CRCC)|Chinese Embassy|CITIC Group Corporation",
        "recipient": "Government of Algeria"
      },
      {
        "id": 62369,
        "year": 2010,
        "title": "Chinese Government dispatches 22nd medical team to Algiers, Aïn Defla, Tiaret, Sétif, Khenchela, Batna, Mascara, and Saïda",
        "sector": "HEALTH",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Unspecified Chinese Government Institution",
        "recipient": "Government of Algeria"
      },
      {
        "id": 31785,
        "year": 2009,
        "title": "Chinese Government provides grant for Phase 1 of Saline Farmland Improvement Project (Linked to Project ID#53202)",
        "sector": "AGRICULTURE, FORESTRY, FISHING",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "China Ministry of Commerce",
        "recipient": "Government of Algeria"
      },
      {
        "id": 85231,
        "year": 2009,
        "title": "China Earthquake Administration provides EUR 1 million grant for Seismological Station Installation Project",
        "sector": "DISASTER PREVENTION AND PREPAREDNESS",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 2086580,
        "recommended": true,
        "funder": "China Earthquake Administration",
        "recipient": "Algeria Center for Research in Astronomy, Astrophysics and Geophysics (CRAAG)"
      },
      {
        "id": 35579,
        "year": 2008,
        "title": "Chinese Government provides 76 scholarships to Algerian students",
        "sector": "EDUCATION",
        "flowType": "Grant",
        "status": "Implementation",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Unspecified Chinese Government Institution",
        "recipient": "Government of Algeria"
      },
      {
        "id": 85235,
        "year": 2008,
        "title": "Chinese Government dispatches 21st medical team to Algiers, Aïn Defla, Tiaret, Sétif, Khenchela, Batna, Mascara, and Saïda",
        "sector": "HEALTH",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Unspecified Chinese Government Institution",
        "recipient": "Government of Algeria"
      },
      {
        "id": 90350,
        "year": 2008,
        "title": "Chinese Embassy in Algeria Donates 1,000 Books and Other Equipment to the National Library of Algeria",
        "sector": "EDUCATION",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Chinese Embassy",
        "recipient": "National Library of Algeria"
      },
      {
        "id": 624,
        "year": 2007,
        "title": "ZTE provides grant for North African Training Academy and donates $500,000 of telecommunications equipment",
        "sector": "COMMUNICATIONS",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 899632,
        "recommended": true,
        "funder": "ZTE Corporation",
        "recipient": "Algerian Ministry of Post, Information Technology, and Communication"
      },
      {
        "id": 61424,
        "year": 2007,
        "title": "Chinese Government donates sports equipment worth RMB 100,000",
        "sector": "OTHER SOCIAL INFRASTRUCTURE AND SERVICES",
        "flowType": "Grant",
        "status": "Pipeline: Commitment",
        "amountUSD": 23655,
        "recommended": true,
        "funder": "Unspecified Chinese Government Institution",
        "recipient": "Government of Algeria"
      },
      {
        "id": 85234,
        "year": 2007,
        "title": "Chinese Government dispatches 20th medical team to Algiers, Aïn Defla, Tiaret, Sétif, Khenchela, Batna, Mascara, and Saïda",
        "sector": "HEALTH",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Provincial Government of Hubei (China)|Unspecified Chinese Government Institution",
        "recipient": "Government of Algeria"
      },
      {
        "id": 529,
        "year": 2005,
        "title": "MOFCOM provides $30 million interest-free loan for Ministry of Foreign Affairs Office Building Construction Project",
        "sector": "GOVERNMENT AND CIVIL SOCIETY",
        "flowType": "Loan",
        "status": "Completion",
        "amountUSD": 65107000,
        "recommended": true,
        "funder": "China Ministry of Commerce",
        "recipient": "Government of Algeria"
      },
      {
        "id": 85233,
        "year": 2005,
        "title": "Chinese Government dispatches 19th medical team to Algiers, Aïn Defla, Tiaret, Sétif, Khenchela, Batna, Mascara, and Saïda",
        "sector": "HEALTH",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Unspecified Chinese Government Institution",
        "recipient": "Government of Algeria"
      },
      {
        "id": 330,
        "year": 2004,
        "title": "China Eximbank pledges $48 million loan — via framework agreement — for unspecified purposes",
        "sector": "UNALLOCATED/UNSPECIFIED",
        "flowType": "Loan",
        "status": "Pipeline: Pledge",
        "amountUSD": 109327302,
        "recommended": false,
        "funder": "Export-Import Bank of China (China Eximbank)",
        "recipient": "Government of Algeria"
      },
      {
        "id": 516,
        "year": 2004,
        "title": "Chinese Government provides RMB 10 million grant — via ETCA — for Fixed Seismic Observation Network Project",
        "sector": "DISASTER PREVENTION AND PREPAREDNESS",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 2751809,
        "recommended": true,
        "funder": "China Ministry of Commerce",
        "recipient": "Government of Algeria"
      },
      {
        "id": 62309,
        "year": 2004,
        "title": "Chinese Government donates televisions, computers, children’s blankets, stationery and children’s toys",
        "sector": "OTHER COMMODITY ASSISTANCE",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Unspecified Chinese Government Institution",
        "recipient": "Government of Algeria"
      },
      {
        "id": 14,
        "year": 2003,
        "title": "Chinese Government provides RMB 5 million grant for Boumerdès earthquake response activities",
        "sector": "EMERGENCY RESPONSE",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 1471569,
        "recommended": true,
        "funder": "Unspecified Chinese Government Institution",
        "recipient": "Government of Algeria"
      },
      {
        "id": 20,
        "year": 2003,
        "title": "ICBC and Société Générale provides $40 million buyer’s credit loan for CDMA WLL Local Telephone Project",
        "sector": "COMMUNICATIONS",
        "flowType": "Loan",
        "status": "Completion",
        "amountUSD": 48721275,
        "recommended": true,
        "funder": "Industrial and Commercial Bank of China (ICBC)",
        "recipient": "Algérie Télécom"
      },
      {
        "id": 62969,
        "year": 2003,
        "title": "Chinese Government dispatches experts to advise on reconstruction planning after 2003 Boumerdès earthquake (Linked to Project ID#14)",
        "sector": "RECONSTRUCTION RELIEF AND REHABILITATION",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Unspecified Chinese Government Institution",
        "recipient": "Government of Algeria"
      },
      {
        "id": 62970,
        "year": 2003,
        "title": "Chinese Government donates 10,000 radios to support Boumerdès earthquake relief efforts",
        "sector": "EMERGENCY RESPONSE",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Unspecified Chinese Government Institution",
        "recipient": "Government of Algeria"
      },
      {
        "id": 73663,
        "year": 2003,
        "title": "China sends International Rescue Team to Algeria following the 2003 Boumerdès earthquake",
        "sector": "EMERGENCY RESPONSE",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Unspecified Chinese Government Institution",
        "recipient": ""
      },
      {
        "id": 272,
        "year": 2002,
        "title": "Chinese Government provides $6 million interest-free loan — via ETCA — for unspecified purposes",
        "sector": "UNALLOCATED/UNSPECIFIED",
        "flowType": "Loan",
        "status": "Pipeline: Commitment",
        "amountUSD": 14996729,
        "recommended": false,
        "funder": "China Ministry of Commerce",
        "recipient": "Government of Algeria"
      },
      {
        "id": 332,
        "year": 2002,
        "title": "Chinese Government provides $3 million interest-free loan — via ETCA — for unspecified purposes",
        "sector": "UNALLOCATED/UNSPECIFIED",
        "flowType": "Loan",
        "status": "Pipeline: Commitment",
        "amountUSD": 7498365,
        "recommended": false,
        "funder": "China Ministry of Commerce",
        "recipient": "Government of Algeria"
      },
      {
        "id": 21879,
        "year": 2002,
        "title": "Chinese Government dispatches 18th medical team to Algiers, Aïn Defla, Tiaret, Sétif, Khenchela, Batna, Mascara, and Saïda",
        "sector": "HEALTH",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Unspecified Chinese Government Institution",
        "recipient": "Government of Algeria"
      },
      {
        "id": 22429,
        "year": 2002,
        "title": "Chinese Government funds Guelma Ceramic Factory Reconstruction Project",
        "sector": "INDUSTRY, MINING, CONSTRUCTION",
        "flowType": "Vague",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "China Ministry of Commerce",
        "recipient": "Government of Algeria"
      },
      {
        "id": 85232,
        "year": 2000,
        "title": "Chinese Government dispatches 17th medical team to Algiers, Aïn Defla, Tiaret, Sétif, Khenchela, Batna, Mascara, and Saïda",
        "sector": "HEALTH",
        "flowType": "Grant",
        "status": "Completion",
        "amountUSD": 0,
        "recommended": true,
        "funder": "Unspecified Chinese Government Institution",
        "recipient": "Government of Algeria"
      }
    ]
  }
};
